export default {
    data: () => {
        return {
            tabs: [
                {
                    title: "Sharky is my best friend.",
                    paragraph1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo a diam sollicitudin tempor id eu. Eros in cursus turpis massa tincidunt dui ut ornare. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. Lorem ipsum dolor sit amet consectetur adipiscing. Diam vulputate ut pharetra sit. Amet nisl purus in mollis nunc sed id. Morbi tristique senectus et netus et malesuada. Varius duis at consectetur lorem donec. Pellentesque adipiscing commodo elit at imperdiet dui accumsan. Odio euismod lacinia at quis. Quis hendrerit dolor magna eget est lorem. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. At augue eget arcu dictum varius duis.",
                    paragraph2: "Blandit libero volutpat sed cras ornare arcu. Dui nunc mattis enim ut tellus elementum sagittis vitae et. Quis commodo odio aenean sed adipiscing diam donec. Lobortis elementum nibh tellus molestie nunc non blandit massa enim. Sed felis eget velit aliquet sagittis id consectetur. Risus nullam eget felis eget. In arcu cursus euismod quis viverra nibh. Nulla facilisi morbi tempus iaculis urna. Egestas purus viverra accumsan in. Et netus et malesuada fames ac turpis egestas maecenas. Arcu felis bibendum ut tristique et egestas. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Varius quam quisque id diam vel quam elementum pulvinar etiam. A cras semper auctor neque vitae tempus quam. Vestibulum lectus mauris ultrices eros. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Malesuada fames ac turpis egestas maecenas.",
                    paragraph3: "Pretium aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Tristique magna sit amet purus gravida quis blandit turpis cursus. Aliquam vestibulum morbi blandit cursus. Molestie nunc non blandit massa enim nec dui. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Quam id leo in vitae. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed velit. Amet consectetur adipiscing elit ut aliquam purus sit. Lobortis feugiat vivamus at augue eget. Dui ut ornare lectus sit. Sed turpis tincidunt id aliquet risus feugiat in ante metus. Consectetur purus ut faucibus pulvinar elementum. Massa sapien faucibus et molestie ac. Ac turpis egestas sed tempus urna. Enim blandit volutpat maecenas volutpat blandit aliquam. Ut sem viverra aliquet eget sit amet tellus cras. Ornare arcu dui vivamus arcu felis bibendum ut tristique et.",
                    paragraph4: "Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus est. Erat nam at lectus urna. Nunc scelerisque viverra mauris in. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Mauris nunc congue nisi vitae suscipit tellus mauris a. Ultricies mi eget mauris pharetra et. Mattis enim ut tellus elementum sagittis vitae et leo duis. Elit ut aliquam purus sit. Cras fermentum odio eu feugiat pretium. Placerat vestibulum lectus mauris ultrices eros in cursus turpis massa. Non pulvinar neque laoreet suspendisse interdum consectetur libero. Nunc congue nisi vitae suscipit. Sed id semper risus in hendrerit gravida rutrum quisque. Morbi tempus iaculis urna id volutpat lacus laoreet non curabitur. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Dolor magna eget est lorem ipsum dolor. Netus et malesuada fames ac turpis egestas maecenas. Amet commodo nulla facilisi nullam vehicula ipsum a. Feugiat vivamus at augue eget. Odio morbi quis commodo odio aenean sed adipiscing diam.",
                    paragraph5: "Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Scelerisque fermentum dui faucibus in ornare. Faucibus turpis in eu mi. Vel facilisis volutpat est velit. Pretium lectus quam id leo in vitae. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Leo a diam sollicitudin tempor id eu nisl. Varius vel pharetra vel turpis nunc eget lorem dolor sed. Tristique nulla aliquet enim tortor at auctor. Accumsan sit amet nulla facilisi morbi tempus iaculis urna id. Sed egestas egestas fringilla phasellus. Tempor id eu nisl nunc mi. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui. Ut tellus elementum sagittis vitae et leo duis ut diam. Vitae suscipit tellus mauris a diam maecenas. Quis ipsum suspendisse ultrices gravida dictum. Amet mauris commodo quis imperdiet massa tincidunt nunc. Mi bibendum neque egestas congue.",
                },
                {
                    title: "Kaitlin is my best friend.",
                    paragraph1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper auctor neque vitae tempus quam pellentesque nec nam aliquam. Penatibus et magnis dis parturient montes nascetur. Lorem ipsum dolor sit amet. Phasellus vestibulum lorem sed risus. Adipiscing bibendum est ultricies integer quis auctor elit sed. Sit amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Ac placerat vestibulum lectus mauris ultrices eros in cursus turpis. Dui accumsan sit amet nulla. Amet nulla facilisi morbi tempus iaculis. Quis hendrerit dolor magna eget est. Sed ullamcorper morbi tincidunt ornare massa eget. Elit pellentesque habitant morbi tristique senectus et netus.",
                    paragraph2: "Morbi blandit cursus risus at ultrices. Massa eget egestas purus viverra. Pharetra sit amet aliquam id diam maecenas ultricies mi. Amet justo donec enim diam vulputate ut pharetra. Id interdum velit laoreet id donec ultrices tincidunt arcu. Vitae ultricies leo integer malesuada nunc vel risus. Sit amet consectetur adipiscing elit ut aliquam purus sit. Dolor magna eget est lorem ipsum dolor. Massa vitae tortor condimentum lacinia quis. Libero nunc consequat interdum varius sit amet. Leo vel fringilla est ullamcorper. Magna sit amet purus gravida quis blandit turpis. Ipsum dolor sit amet consectetur adipiscing. Dui id ornare arcu odio ut sem nulla pharetra. Viverra vitae congue eu consequat ac felis donec. Urna condimentum mattis pellentesque id nibh tortor id.",
                    paragraph3: "Ante in nibh mauris cursus. Interdum consectetur libero id faucibus nisl. Velit aliquet sagittis id consectetur purus ut. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius sit. Scelerisque eu ultrices vitae auctor eu augue ut. Tellus orci ac auctor augue mauris augue neque. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Ut diam quam nulla porttitor massa. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Sed faucibus turpis in eu mi bibendum neque egestas congue. Etiam sit amet nisl purus in mollis nunc sed. Dis parturient montes nascetur ridiculus mus mauris. Suspendisse sed nisi lacus sed viverra tellus. Nibh tellus molestie nunc non blandit massa enim nec.",
                    paragraph4: "In cursus turpis massa tincidunt dui. Porttitor lacus luctus accumsan tortor posuere ac ut consequat. Eget sit amet tellus cras adipiscing enim eu turpis egestas. Erat velit scelerisque in dictum non consectetur a erat. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Pellentesque sit amet porttitor eget dolor. Mattis molestie a iaculis at erat. Semper viverra nam libero justo laoreet. Facilisis volutpat est velit egestas dui id ornare arcu. Adipiscing commodo elit at imperdiet dui accumsan sit amet nulla. Dictum at tempor commodo ullamcorper a. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Sociis natoque penatibus et magnis. Augue ut lectus arcu bibendum at. Egestas diam in arcu cursus euismod quis viverra nibh cras. Eget nunc scelerisque viverra mauris in. Magna fringilla urna porttitor rhoncus dolor purus non. Tellus in metus vulputate eu scelerisque felis imperdiet.",
                    paragraph5: "Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Amet justo donec enim diam vulputate. Nunc sed velit dignissim sodales. Convallis aenean et tortor at risus. At elementum eu facilisis sed odio morbi quis commodo. Sit amet aliquam id diam maecenas ultricies mi eget mauris. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Malesuada fames ac turpis egestas integer eget aliquet. Ut diam quam nulla porttitor massa id neque aliquam vestibulum. Vel eros donec ac odio tempor orci dapibus ultrices in. Tempor nec feugiat nisl pretium fusce id velit. Vel fringilla est ullamcorper eget.",
                },
                {
                    title: "Your PP is small, new studies suggest.",
                    paragraph1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mauris cursus mattis molestie a iaculis at erat. Integer quis auctor elit sed vulputate. Mauris vitae ultricies leo integer malesuada nunc. Nulla facilisi cras fermentum odio eu. Leo in vitae turpis massa sed elementum. Arcu non odio euismod lacinia at quis risus sed. Ut pharetra sit amet aliquam id. Arcu odio ut sem nulla pharetra. Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Adipiscing commodo elit at imperdiet dui accumsan sit. Integer malesuada nunc vel risus commodo viverra. Pharetra diam sit amet nisl suscipit adipiscing bibendum est. Nibh ipsum consequat nisl vel pretium lectus quam id leo. Tristique senectus et netus et malesuada fames ac. Nibh venenatis cras sed felis eget velit. Enim ut sem viverra aliquet eget sit.",
                    paragraph2: "Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Iaculis eu non diam phasellus. Libero justo laoreet sit amet cursus. Mauris pharetra et ultrices neque ornare aenean euismod elementum. Faucibus pulvinar elementum integer enim neque volutpat. Vel quam elementum pulvinar etiam non quam lacus suspendisse. Id aliquet lectus proin nibh nisl. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet. Tristique risus nec feugiat in fermentum posuere urna. Sem et tortor consequat id porta nibh venenatis. Libero id faucibus nisl tincidunt eget. Ut sem nulla pharetra diam sit amet nisl suscipit adipiscing.",
                    paragraph3: "Lacus laoreet non curabitur gravida arcu. Volutpat est velit egestas dui id ornare arcu odio. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Lacus viverra vitae congue eu consequat. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Tortor consequat id porta nibh venenatis cras sed. Sed blandit libero volutpat sed. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. At risus viverra adipiscing at in tellus integer. Vel eros donec ac odio tempor orci dapibus. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Neque viverra justo nec ultrices dui sapien eget mi proin. Porttitor eget dolor morbi non arcu risus quis varius quam. Enim tortor at auctor urna nunc. Ipsum suspendisse ultrices gravida dictum. Sapien faucibus et molestie ac feugiat. Mattis enim ut tellus elementum. Tristique senectus et netus et malesuada. Magnis dis parturient montes nascetur ridiculus mus mauris vitae ultricies.",
                    paragraph4: "At tellus at urna condimentum mattis pellentesque id. Duis at tellus at urna condimentum mattis pellentesque id. Vel risus commodo viverra maecenas accumsan lacus. Et leo duis ut diam quam nulla. Fermentum et sollicitudin ac orci phasellus. Integer quis auctor elit sed vulputate mi sit. Lectus nulla at volutpat diam ut venenatis tellus. Porttitor rhoncus dolor purus non enim. Condimentum vitae sapien pellentesque habitant morbi. Sit amet consectetur adipiscing elit duis tristique sollicitudin. Accumsan tortor posuere ac ut consequat semper viverra. Blandit volutpat maecenas volutpat blandit. Nullam eget felis eget nunc lobortis mattis aliquam faucibus purus. A scelerisque purus semper eget duis at tellus at urna. Odio eu feugiat pretium nibh ipsum consequat nisl vel. Ultrices mi tempus imperdiet nulla. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Suspendisse potenti nullam ac tortor vitae.",
                    paragraph5: "Quam lacus suspendisse faucibus interdum. Nunc congue nisi vitae suscipit tellus mauris a. Pellentesque elit ullamcorper dignissim cras tincidunt. Scelerisque varius morbi enim nunc faucibus a. Viverra vitae congue eu consequat ac felis donec et odio. Varius duis at consectetur lorem donec massa sapien faucibus. Libero nunc consequat interdum varius. Mattis rhoncus urna neque viverra justo. Quisque sagittis purus sit amet volutpat consequat mauris. Mi quis hendrerit dolor magna eget est lorem ipsum. Nullam non nisi est sit amet facilisis magna. Ipsum a arcu cursus vitae congue mauris rhoncus.",
                },
                {
                    title: "",
                    paragraph1: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Risus at ultrices mi tempus imperdiet nulla. Viverra nibh cras pulvinar mattis. In ante metus dictum at tempor commodo ullamcorper a. Leo duis ut diam quam nulla porttitor massa id. Fusce id velit ut tortor pretium viverra. Ultricies mi quis hendrerit dolor. Nec feugiat nisl pretium fusce. Odio euismod lacinia at quis risus. Pharetra convallis posuere morbi leo. Bibendum est ultricies integer quis auctor. Justo nec ultrices dui sapien eget mi proin sed. Nisl condimentum id venenatis a. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Aliquam sem et tortor consequat id. Arcu dictum varius duis at consectetur lorem donec massa sapien. At imperdiet dui accumsan sit. Nec tincidunt praesent semper feugiat nibh sed. In iaculis nunc sed augue lacus viverra. Nunc id cursus metus aliquam eleifend.",
                    paragraph2: "Cursus risus at ultrices mi tempus. Amet nisl purus in mollis nunc. Consectetur libero id faucibus nisl tincidunt. Condimentum mattis pellentesque id nibh tortor id. Convallis convallis tellus id interdum velit. Eget nulla facilisi etiam dignissim. Vulputate ut pharetra sit amet aliquam. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Amet dictum sit amet justo donec. Senectus et netus et malesuada fames ac turpis egestas maecenas. Nunc id cursus metus aliquam eleifend. Sed risus ultricies tristique nulla aliquet enim. Varius vel pharetra vel turpis nunc eget lorem dolor sed. Eros in cursus turpis massa tincidunt dui ut. Neque laoreet suspendisse interdum consectetur. Risus nec feugiat in fermentum. Gravida neque convallis a cras semper. Semper auctor neque vitae tempus quam pellentesque nec nam aliquam. Massa sed elementum tempus egestas sed. A cras semper auctor neque vitae tempus.",
                    paragraph3: "Nunc scelerisque viverra mauris in aliquam sem fringilla. Tincidunt nunc pulvinar sapien et. Pulvinar mattis nunc sed blandit libero volutpat sed cras ornare. Mattis rhoncus urna neque viverra. Nunc congue nisi vitae suscipit. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Mi quis hendrerit dolor magna eget est lorem ipsum dolor. Sem fringilla ut morbi tincidunt augue interdum. Et tortor consequat id porta nibh venenatis cras sed felis. Id nibh tortor id aliquet lectus proin. Eget mi proin sed libero enim sed faucibus. Ultricies lacus sed turpis tincidunt id. Amet mauris commodo quis imperdiet. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu.",
                    paragraph4: "Amet consectetur adipiscing elit pellentesque. Adipiscing at in tellus integer feugiat scelerisque varius. Vitae suscipit tellus mauris a diam maecenas sed enim ut. Cursus euismod quis viverra nibh cras. Odio morbi quis commodo odio. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Sit amet nisl purus in mollis nunc. Et leo duis ut diam quam nulla porttitor massa id. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Dui sapien eget mi proin sed libero enim. Consectetur a erat nam at lectus urna duis convallis. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet enim. Vel orci porta non pulvinar neque laoreet. Faucibus pulvinar elementum integer enim.",
                    paragraph5: "A condimentum vitae sapien pellentesque habitant. Amet mauris commodo quis imperdiet massa. Viverra vitae congue eu consequat ac felis donec et odio. Euismod quis viverra nibh cras pulvinar mattis nunc sed blandit. Faucibus pulvinar elementum integer enim neque. Tellus id interdum velit laoreet. Curabitur vitae nunc sed velit dignissim sodales ut. Bibendum enim facilisis gravida neque convallis. Hac habitasse platea dictumst quisque sagittis purus sit. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Sem et tortor consequat id. Ac tortor dignissim convallis aenean et tortor at. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Tempus imperdiet nulla malesuada pellentesque. Tempor orci eu lobortis elementum nibh tellus molestie. Id interdum velit laoreet id donec ultrices tincidunt arcu. Proin sagittis nisl rhoncus mattis.",
                },
            ],
        };
    },
};